version: '3'

services:
  app:
    build: .
    container_name: 'notification-api-app'
    command: npm start
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge